-- Video formats
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('DCP 2K');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('DCP 4K');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('DCP 3D');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('IMAX 2D');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('IMAX 3D');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('4DX');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('ScreenX');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('35mm');
INSERT INTO VIDEO_FORMATS (VIDEO_FORMAT_NAME) VALUES ('70mm');

-- Audio formats
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('Stereo (2.0)');
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('5.1 Surround');
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('7.1 Surround');
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('Dolby Atmos');
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('DTS:X');
INSERT INTO AUDIO_FORMATS (AUDIO_FORMAT_NAME) VALUES ('Auro 3D');

-- Audiovisual formats (excludes existing ones)
INSERT INTO AUDIOVISUAL_FORMATS (ID_VIDEO_FORMAT, ID_AUDIO_FORMAT)
SELECT v.ID_VIDEO_FORMAT, a.ID_AUDIO_FORMAT
FROM VIDEO_FORMATS v
CROSS JOIN AUDIO_FORMATS a
WHERE NOT EXISTS (
  SELECT 1
  FROM AUDIOVISUAL_FORMATS avf
  WHERE avf.ID_VIDEO_FORMAT = v.ID_VIDEO_FORMAT
    AND avf.ID_AUDIO_FORMAT = a.ID_AUDIO_FORMAT
);

COMMIT;

-- Make sure all combinations of audio and video are unique
ALTER TABLE AUDIOVISUAL_FORMATS
    ADD CONSTRAINT UQ_AUDIOVISUAL_FORMAT UNIQUE (ID_VIDEO_FORMAT, ID_AUDIO_FORMAT);