CREATE TABLE CLIENTS (
    ID_CLIENT NUMBER GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR2(254) NOT NULL,
    IDENTIFICATION_TYPE CHAR(1) NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR2(20) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    MIDDLE_NAME VARCHAR2(50),
    FIRST_SURNAME VARCHAR2(50) NOT NULL,
    LAST_SURNAME VARCHAR2(50),
    BIRTHDATE DATE NOT NULL
);

CREATE TABLE CREDENTIALS (
    ID_CREDENTIAL NUMBER GENERATED ALWAYS AS IDENTITY,
    HASH VARCHAR2(255) NOT NULL, --hash de bcrypt trae el salt incluido dentro del hash
    LAST_CHANGED_DATE DATE DEFAULT SYSDATE NOT NULL,
    ID_CLIENT NUMBER
);

--Primarykeys
ALTER TABLE CLIENTS ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT);
ALTER TABLE CREDENTIALS ADD CONSTRAINT PK_CREDENTIAL PRIMARY KEY (ID_CREDENTIAL);

--Unique
ALTER TABLE CLIENTS ADD CONSTRAINT UQ_CLIENT_EMAIL UNIQUE (EMAIL);
ALTER TABLE CLIENTS ADD CONSTRAINT UQ_CLIENT_IDENTIFICATION UNIQUE (IDENTIFICATION_NUMBER);
ALTER TABLE CREDENTIALS ADD CONSTRAINT UQ_CREDENTIAL_CLIENT UNIQUE (ID_CLIENT);

--Validations
ALTER TABLE CLIENTS ADD CONSTRAINT CHK_CLIENT_EMAIL_LOWER CHECK (EMAIL = LOWER(EMAIL));
ALTER TABLE CLIENTS ADD CONSTRAINT CHK_CLIENT_IDENTIFICATION_TYPE CHECK (IDENTIFICATION_TYPE IN ('C', 'P', 'D'));
ALTER TABLE CREDENTIALS ADD CONSTRAINT CHK_CREDENTIAL_OWNER CHECK (ID_CLIENT IS NOT NULL);

--Foreignkeys
ALTER TABLE CREDENTIALS ADD CONSTRAINT FK_CREDENTIAL_CLIENT
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT);

--Permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON PI_DEVELOPERS.CLIENTS TO SERVER;
GRANT SELECT, INSERT, UPDATE, DELETE ON PI_DEVELOPERS.CREDENTIALS TO SERVER;
