CREATE TABLE DISCOUNTS (
    ID_DISCOUNTS NUMBER(6) CONSTRAINT PL_ID_DISC PRIMARY KEY,
    DISCOUNT_START_DATE DATE CONSTRAINT NN_START_DATE_DISC NOT NULL,
    DISCOUNT_FINISH_DATE DATE CONSTRAINT NN_FIN_DATE_DISC NOT NULL,
    DISCOUNT_PORCENTAGE NUMBER(3) CONSTRAINT NN_PORCENTAGE_DISC NOT NULL,
);

ALTER TABLE DISCOUNTS
ADD ID_SNACKS NUMBER CONSTRAINT FK_SNACKS_ID_DISC REFERENCES SNACKS(ID_SNACK);

ALTER TABLE DISCOUNTS
ADD ID_MOVIE_IN_BILLBOARD NUMBER CONSTRAINT FK_ID_MOV_BILL_DISC REFERENCES MOVIES_IN_BILLBOARDS(ID_MOVIE_IN_BILLBOARD),

ALTER TABLE DISCOUNTS
RENAME COLUMN ID_DISCOUNTS TO ID_DISCOUNT;

ALTER TABLE DISCOUNTS
ADD DISCOUNT_NAME VARCHAR(50) CONSTRAINT NN_NAME_DISC NOT NULL;

GRANT SELECT, INSERT, UPDATE, DELETE ON PI_DEVELOPERS.DISCOUNTS TO SERVER;