CREATE TABLE DISCOUNTS (
    ID_DISCOUNTS NUMBER(6) CONSTRAINT PL_ID_DISC PRIMARY KEY,
    DISCOUNT_START_DATE DATE CONSTRAINT NN_START_DATE_DISC NOT NULL,
    DISCOUNT_FINISH_DATE DATE CONSTRAINT NN_FIN_DATE_DISC NOT NULL,
    DISCOUNT_PORCENTAGE NUMBER(3) CONSTRAINT NN_PORCENTAGE_DISC NOT NULL,
);

ALTER TABLE DISCOUNTS
ADD ID_SNACKS NUMBER CONSTRAINT FK_SNACKS_ID_DISC REFERENCES SNACKS(ID_SNACK)

ALTER TABLE DISCOUNTS
ADD ID_MOVIE_IN_BILLBOARD NUMBER CONSTRAINT FK_ID_MOV_BILL_DISC REFERENCES MOVIES_IN_BILLBOARDS(ID_MOVIE_IN_BILLBOARD)