--Requires AUDIOVISUAL_FORMATS (movies.sql)
CREATE TABLE FEES (
    ID_FEE NUMBER GENERATED ALWAYS AS IDENTITY,
    TYPE CHAR(1) NOT NULL,
    AMOUNT NUMBER(10, 2) NOT NULL,
    ID_AUDIOVISUAL_FORMAT NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

--Primarykeys
ALTER TABLE FEES ADD CONSTRAINT PK_FEE PRIMARY KEY (ID_FEE);

--Unique, only one active fee per type and audiovisual format
CREATE UNIQUE INDEX UQ_FEE_TYPE_FORMAT ON FEES (
    CASE WHEN IS_DELETED = 0 THEN TYPE END,
    CASE WHEN IS_DELETED = 0 THEN ID_AUDIOVISUAL_FORMAT END);

--Validations
ALTER TABLE FEES ADD CONSTRAINT CHK_FEE_TYPE CHECK (TYPE IN ('G', 'N', 'E', 'M'));
ALTER TABLE FEES ADD CONSTRAINT CHK_FEE_AMOUNT CHECK (AMOUNT > 0);
ALTER TABLE FEES ADD CONSTRAINT CHK_FEE_DELETED CHECK (IS_DELETED IN (0, 1));

--Foreignkeys
ALTER TABLE FEES ADD CONSTRAINT FK_FEE_AUDIOVISUAL_FORMAT
    FOREIGN KEY (ID_AUDIOVISUAL_FORMAT) REFERENCES AUDIOVISUAL_FORMATS(ID_AUDIOVISUAL_FORMAT);

--Permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON PI_DEVELOPERS.FEES TO SERVER;
