-- Tables
CREATE TABLE PROVINCES (
    ID_PROVINCE NUMBER GENERATED ALWAYS AS IDENTITY,
    PROVINCE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE CANTONS (
    ID_CANTON NUMBER GENERATED ALWAYS AS IDENTITY,
    CANTON_NAME VARCHAR2(30) NOT NULL,
    ID_PROVINCE NUMBER NOT NULL
);

CREATE TABLE LOCATIONS (
    ID_LOCATION NUMBER GENERATED ALWAYS AS IDENTITY,
    LOCATION_NAME VARCHAR2(30) NOT NULL,
    OPENING_HOUR INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    CLOSING_HOUR INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

-- Primary Keys
ALTER TABLE PROVINCES ADD CONSTRAINT PK_PROVINCE PRIMARY KEY (ID_PROVINCE);
ALTER TABLE CANTONS ADD CONSTRAINT PK_CANTON PRIMARY KEY (ID_CANTON);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATION PRIMARY KEY (ID_LOCATION);

-- Deletion
ALTER TABLE LOCATIONS ADD CONSTRAINT CHK_LOC_DELETED CHECK (IS_DELETED IN (0, 1));

-- Foreign Keys
ALTER TABLE CANTONS ADD CONSTRAINT FK_CANTON_PROVINCE
    FOREIGN KEY (ID_PROVINCE) REFERENCES PROVINCES(ID_PROVINCE);

ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOCATION_CANTON
    FOREIGN KEY (ID_CANTON) REFERENCES CANTONS(ID_CANTON);