-- Tables
CREATE TABLE MOVIES (
    ID_MOVIE NUMBER GENERATED ALWAYS AS IDENTITY,
    MOVIE_TITLE VARCHAR2(100) NOT NULL,
    SYNOPSIS VARCHAR2(1000) NOT NULL,
    MOVIE_DURATION NUMBER NOT NULL,
    POSTER VARCHAR2(500) NOT NULL, -- Almacena el enlace a la imagen. El servidor debe guardar la imagen en otro lugar.
    ID_RATING NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GENRES (
    ID_GENRE NUMBER GENERATED ALWAYS AS IDENTITY,
    GENRE_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE MOVIES_GENRES (
    ID_MOVIE_GENRE NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MOVIE NUMBER NOT NULL,
    ID_GENRE NUMBER NOT NULL
);

CREATE TABLE DIRECTORS (
    ID_DIRECTOR NUMBER GENERATED ALWAYS AS IDENTITY,
    DIRECTOR_FIRST_NAME VARCHAR2(30) NOT NULL,
    DIRECTOR_LAST_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MOVIES_DIRECTORS (
    ID_MOVIE_DIRECTOR NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MOVIE NUMBER NOT NULL,
    ID_DIRECTOR NUMBER NOT NULL
);

CREATE TABLE VIDEO_FORMATS (
    ID_VIDEO_FORMAT NUMBER GENERATED ALWAYS AS IDENTITY,
    VIDEO_FORMAT_NAME VARCHAR2(30) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE AUDIO_FORMATS (
    ID_AUDIO_FORMAT NUMBER GENERATED ALWAYS AS IDENTITY,
    AUDIO_FORMAT_NAME VARCHAR2(30) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE AUDIOVISUAL_FORMATS (
    ID_AUDIOVISUAL_FORMAT NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_VIDEO_FORMAT NUMBER NOT NULL,
    ID_AUDIO_FORMAT NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MOVIES_FORMATS (
    ID_MOVIE_FORMAT NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MOVIE NUMBER NOT NULL,
    ID_AUDIOVISUAL_FORMAT NUMBER NOT NULL
);

CREATE TABLE LANGUAGES (
    ISO_CODE VARCHAR2(3) NOT NULL,
    LANGUAGE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MOVIES_LANGUAGES (
    ID_MOVIE_LANGUAGE NUMBER GENERATED ALWAYS AS IDENTITY,
    LANGUAGE_TYPE VARCHAR2(3) NOT NULL,
    ID_MOVIE NUMBER NOT NULL,
    ISO_CODE VARCHAR2(10) NOT NULL
);

CREATE TABLE RATINGS (
    ID_RATING NUMBER GENERATED ALWAYS AS IDENTITY,
    RATING_NAME VARCHAR2(30) NOT NULL,
    RATING_CODE VARCHAR2(5) NOT NULL
);

-- Primary Keys
ALTER TABLE MOVIES ADD CONSTRAINT PK_MOVIES PRIMARY KEY (ID_MOVIE);
ALTER TABLE GENRES ADD CONSTRAINT PK_GENRES PRIMARY KEY (ID_GENRE);
ALTER TABLE MOVIES_GENRES ADD CONSTRAINT PK_MOVIES_GENRES PRIMARY KEY (ID_MOVIE_GENRE);
ALTER TABLE DIRECTORS ADD CONSTRAINT PK_DIRECTORS PRIMARY KEY (ID_DIRECTOR);
ALTER TABLE MOVIES_DIRECTORS ADD CONSTRAINT PK_MOVIES_DIRECTORS PRIMARY KEY (ID_MOVIE_DIRECTOR);
ALTER TABLE VIDEO_FORMATS ADD CONSTRAINT PK_VIDEO_FORMATS PRIMARY KEY (ID_VIDEO_FORMAT);
ALTER TABLE AUDIO_FORMATS ADD CONSTRAINT PK_AUDIO_FORMATS PRIMARY KEY (ID_AUDIO_FORMAT);
ALTER TABLE AUDIOVISUAL_FORMATS ADD CONSTRAINT PK_AUDIOVISUAL_FORMATS PRIMARY KEY (ID_AUDIOVISUAL_FORMAT);
ALTER TABLE MOVIES_FORMATS ADD CONSTRAINT PK_MOVIES_FORMATS PRIMARY KEY (ID_MOVIE_FORMAT);
ALTER TABLE LANGUAGES ADD CONSTRAINT PK_LANGUAGES PRIMARY KEY (ISO_CODE);
ALTER TABLE MOVIES_LANGUAGES ADD CONSTRAINT PK_MOVIES_LANGUAGES PRIMARY KEY (ID_MOVIE_LANGUAGE);
ALTER TABLE RATINGS ADD CONSTRAINT PK_RATINGS PRIMARY KEY (ID_RATING);

-- Deletion
ALTER TABLE MOVIES ADD CONSTRAINT CHK_MOVIE_DELETED CHECK (IS_DELETED IN (0, 1));
ALTER TABLE VIDEO_FORMATS ADD CONSTRAINT CHK_VIDEOFORMAT_DELETED CHECK (IS_DELETED IN (0, 1));
ALTER TABLE AUDIO_FORMATS ADD CONSTRAINT CHK_AUDIOFORMAT_DELETED CHECK (IS_DELETED IN (0, 1));
ALTER TABLE AUDIOVISUAL_FORMATS ADD CONSTRAINT CHK_AUDVISFORMAT_DELETED CHECK (IS_DELETED IN (0, 1));

-- Validations
ALTER TABLE MOVIES_LANGUAGES ADD CONSTRAINT CHK_MOVIELANGUAGE_TYPE CHECK (LANGUAGE_TYPE IN ('OG', 'DUB', 'SUB'));

-- Foreign Keys
ALTER TABLE MOVIES ADD CONSTRAINT FK_MOVIES_RATINGS
    FOREIGN KEY (ID_RATING) REFERENCES RATINGS(ID_RATING);

ALTER TABLE MOVIES_GENRES ADD CONSTRAINT FK_MOVIEGENRE_MOVIE
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES(ID_MOVIE);

ALTER TABLE MOVIES_GENRES ADD CONSTRAINT FK_MOVIEGENRE_GENRE
    FOREIGN KEY (ID_GENRE) REFERENCES GENRES(ID_GENRE);

ALTER TABLE MOVIES_DIRECTORS ADD CONSTRAINT FK_MOVIEDIRECTOR_MOVIE
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES(ID_MOVIE);

ALTER TABLE MOVIES_DIRECTORS ADD CONSTRAINT FK_MOVIEDIRECTOR_DIRECTOR
    FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTORS(ID_DIRECTOR);

ALTER TABLE AUDIOVISUAL_FORMATS ADD CONSTRAINT FK_AUDVISFORMAT_VIDEO
    FOREIGN KEY (ID_VIDEO_FORMAT) REFERENCES VIDEO_FORMATS(ID_VIDEO_FORMAT);

ALTER TABLE AUDIOVISUAL_FORMATS ADD CONSTRAINT FK_AUDVISFORMAT_AUDIO
    FOREIGN KEY (ID_AUDIO_FORMAT) REFERENCES AUDIO_FORMATS(ID_AUDIO_FORMAT);

ALTER TABLE MOVIES_FORMATS ADD CONSTRAINT FK_MOVIEFORMAT_MOVIE
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES(ID_MOVIE);

ALTER TABLE MOVIES_FORMATS ADD CONSTRAINT FK_MOVIEFORMAT_FORMAT
    FOREIGN KEY (ID_MOVIE_FORMAT) REFERENCES AUDIOVISUAL_FORMATS(ID_AUDIOVISUAL_FORMAT);

ALTER TABLE MOVIES_LANGUAGES ADD CONSTRAINT FK_MOVIELANGUAGE_MOVIE
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES(ID_MOVIE);

ALTER TABLE MOVIES_LANGUAGES ADD CONSTRAINT FK_MOVIELANGUAGE_LANGUAGE
    FOREIGN KEY (ISO_CODE) REFERENCES LANGUAGES(ISO_CODE);