-- Tables
CREATE TABLE MOVIES_IN_BILLBOARDS (
    ID_MOVIE_IN_BILLBOARD NUMBER GENERATED ALWAYS AS IDENTITY,
    OPENING_DATE DATE NOT NULL,
    CLOSING_DATE DATE NOT NULL,
    PREMIER NUMBER(1) DEFAULT 0 NOT NULL,
    ID_LOCATION NUMBER NOT NULL,
    ID_MOVIE NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SCREENINGS (
    ID_SCREENING NUMBER GENERATED ALWAYS AS IDENTITY,
    SCREENING_DATE DATE NOT NULL,
    SCREENING_START_TIME INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    SCREENING_END_TIME INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    MOVIE_LANGUAGE VARCHAR2(50) NOT NULL,
    MOVIE_FORMAT VARCHAR2(50) NOT NULL,
    ID_SCREEN NUMBER NOT NULL,
    ID_MOVIE_IN_BILLBOARD NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

-- Primary Keys
ALTER TABLE MOVIES_IN_BILLBOARDS ADD CONSTRAINT PK_MIB PRIMARY KEY (ID_MOVIE_IN_BILLBOARD);
ALTER TABLE SCREENINGS ADD CONSTRAINT PK_SCREENINGS PRIMARY KEY (ID_SCREENING);

-- Deletion
ALTER TABLE MOVIES_IN_BILLBOARDS ADD CONSTRAINT CHK_MIB_DELETED CHECK (IS_DELETED IN (0, 1));
ALTER TABLE SCREENINGS ADD CONSTRAINT CHK_SCREENING_DELETED CHECK (IS_DELETED IN (0, 1));

-- Validations
ALTER TABLE MOVIES_IN_BILLBOARDS ADD CONSTRAINT CHK_MIB_PREMIER CHECK (PREMIER IN (0, 1));

-- Foreign Keys
ALTER TABLE MOVIES_IN_BILLBOARDS ADD CONSTRAINT FK_MIB_LOCATIONS
    FOREIGN KEY (ID_LOCATION) REFERENCES LOCATIONS(ID_LOCATION);

ALTER TABLE MOVIES_IN_BILLBOARDS ADD CONSTRAINT FK_MIB_MOVIES
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES(ID_MOVIE);

ALTER TABLE SCREENINGS ADD CONSTRAINT FK_SCREENINGS_SCREENS
    FOREIGN KEY (ID_SCREEN) REFERENCES SCREENS(ID_SCREEN);

ALTER TABLE SCREENINGS ADD CONSTRAINT FK_SCREENINGS_BILLBOARDS
    FOREIGN KEY (ID_MOVIE_IN_BILLBOARD) REFERENCES MOVIES_IN_BILLBOARDS(ID_MOVIE_IN_BILLBOARD);