-- Tables
CREATE TABLE SCREENS (
    ID_SCREEN NUMBER GENERATED ALWAYS AS IDENTITY,
    SCREEN_TYPE VARCHAR2(4) NOT NULL,
    AMOUNT_SEATS NUMBER NOT NULL,
    AMOUNT_ROWS NUMBER NOT NULL,
    AMOUNT_SEATS_PER_ROWS NUMBER NOT NULL,
    MAINTENANCE_TIME NUMBER NOT NULL,
    ADDS_TIME NUMBER NOT NULL,
    ID_LOCATION NUMBER NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

-- Primary Keys
ALTER TABLE SCREENS ADD CONSTRAINT PK_SCREEN PRIMARY KEY (ID_SCREEN);

-- Deletion
ALTER TABLE SCREENS ADD CONSTRAINT CHK_SCREEN_DELETED CHECK (IS_DELETED IN (0, 1));

-- Validations
ALTER TABLE SCREENS ADD CONSTRAINT CHK_SCREEN_TYPE CHECK (SCREEN_TYPE IN ('REG', 'VIP', 'IMAX', '4DX'));

-- Foreign Keys
ALTER TABLE SCREENS ADD CONSTRAINT FK_SCREEN_LOCATION
    FOREIGN KEY (ID_LOCATION) REFERENCES LOCATIONS(ID_LOCATION);