-- Requires CLIENTS and CREDENTIALS (clients.sql) and WORKERS (Workers.sql)

-- Columns
ALTER TABLE CREDENTIALS ADD SESSION_VERSION NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE CREDENTIALS ADD ID_WORKER NUMBER;

-- Unique
ALTER TABLE CREDENTIALS ADD CONSTRAINT UQ_CREDENTIAL_WORKER UNIQUE (ID_WORKER);

-- Validations
ALTER TABLE CREDENTIALS DROP CONSTRAINT CHK_CREDENTIAL_OWNER;
ALTER TABLE CREDENTIALS ADD CONSTRAINT CHK_CREDENTIAL_OWNER CHECK (
    (ID_CLIENT IS NOT NULL AND ID_WORKER IS NULL) OR
    (ID_CLIENT IS NULL AND ID_WORKER IS NOT NULL)
);
ALTER TABLE CREDENTIALS ADD CONSTRAINT CHK_CREDENTIAL_SESSION_VERSION CHECK (SESSION_VERSION >= 0);

-- Foreign Keys
ALTER TABLE CREDENTIALS ADD CONSTRAINT FK_CREDENTIAL_WORKER
    FOREIGN KEY (ID_WORKER) REFERENCES WORKERS(ID_WORKER);
