CREATE TABLE SNACKS (
    ID_SNACK NUMBER(6) CONSTRAINT PK_ID_SNACK PRIMARY KEY,
    SNACK_NAME VARCHAR2(20) CONSTRAINT NN_NAME_SNACK NOT NULL,
    SNACK_DESCRIPTION VARCHAR2(100) CONSTRAINT NN_DESC_SNACK NOT NULL,
    SNACK_PRICE NUMBER(6) CONSTRAINT NN_PRICE_SNACK NOT NULL
);

