CREATE TABLE WORKER_LOCATIONS (
    ID_WORKER NUMBER NOT NULL,
    ID_LOCATION NUMBER NOT NULL
);

-- Primary key comp
ALTER TABLE WORKER_LOCATIONS
ADD CONSTRAINT PK_WORKER_LOCATION
PRIMARY KEY (ID_WORKER, ID_LOCATION);

-- Foreign key to WORKERS
ALTER TABLE WORKER_LOCATIONS
ADD CONSTRAINT FK_WORKER_LOCATION_WORKER
FOREIGN KEY (ID_WORKER)
REFERENCES WORKERS(ID_WORKER);

-- Foreign key to LOCATIONS
ALTER TABLE WORKER_LOCATIONS
ADD CONSTRAINT FK_WORKER_LOCATION_LOCATION
FOREIGN KEY (ID_LOCATION)
REFERENCES LOCATIONS(ID_LOCATION);

-- Permissions
GRANT SELECT, INSERT, UPDATE, DELETE
ON PI_DEVELOPERS.WORKER_LOCATIONS TO SERVER;