CREATE TABLE WORKERS (
    ID_WORKER NUMBER GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR2(254) NOT NULL,
    IDENTIFICATION_TYPE CHAR(1) NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR2(20) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    MIDDLE_NAME VARCHAR2(50),
    FIRST_SURNAME VARCHAR2(50) NOT NULL,
    LAST_SURNAME VARCHAR2(50),
    BIRTHDATE DATE NOT NULL,
    ROLE CHAR(1) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Primary key
ALTER TABLE WORKERS
ADD CONSTRAINT PK_WORKER
PRIMARY KEY (ID_WORKER);

-- Unique
ALTER TABLE WORKERS
ADD CONSTRAINT UQ_WORKER_EMAIL
UNIQUE (EMAIL);

ALTER TABLE WORKERS
ADD CONSTRAINT UQ_WORKER_IDENTIFICATION
UNIQUE (IDENTIFICATION_NUMBER);

-- Validations
ALTER TABLE WORKERS
ADD CONSTRAINT CHK_WORKER_EMAIL_LOWER
CHECK (EMAIL = LOWER(EMAIL));

ALTER TABLE WORKERS
ADD CONSTRAINT CHK_WORKER_IDENTIFICATION_TYPE
CHECK (IDENTIFICATION_TYPE IN ('C', 'P', 'D'));

ALTER TABLE WORKERS
ADD CONSTRAINT CHK_WORKER_ROLE
CHECK (ROLE IN ('S', 'A', 'E'));

ALTER TABLE WORKERS
ADD CONSTRAINT CHK_WORKER_ACTIVE
CHECK (IS_ACTIVE IN (0, 1));

-- Permissions
GRANT SELECT, INSERT, UPDATE, DELETE
ON PI_DEVELOPERS.WORKERS TO SERVER;