sonar.exclusions=cinema_app/mui_templates/**,\
  data_base/**,\
  cinema_app/src/theme/datePickers.ts,\
  cinema_app/src/shared-theme/themePrimitives.ts,\
  cinema_app/src/shared-theme/customizations/inputs.tsx